# Generated by Django 3.1.4 on 2020-12-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('avaliability', models.BooleanField(verbose_name='Наличие')),
                ('group', models.CharField(choices=[('Шортики', 'Шортики'), ('Свитшоты', 'Свитшоты'), ('Футболки', 'Футболки'), ('Костюмчики', 'Костюмчики'), ('Шапочки', 'Шапочки'), ('Штанишки', 'Штанишки')], default='Футболки', max_length=20, verbose_name='Тип')),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('size', models.CharField(choices=[('28-30', '28-30'), ('24-26', '24-26'), ('26-28', '26-28')], max_length=10, verbose_name='Размер')),
                ('img', models.ImageField(default='no_image.jpg', upload_to='product_image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукция',
            },
        ),
    ]
